version: '3'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: martindelivery/php
        container_name: martin.app
        restart: always
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - martin-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: martin.nginx
        restart: always
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/conf.d/:/etc/nginx/conf.d/
        networks:
            - martin-network

    db:
        image: mysql:8.0
        container_name: martin.db
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: "martin"
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "martin"
            MYSQL_PASSWORD: "secret"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3304:3306"
        volumes:
            - mysqldata:/var/lib/mysql/
            - ./docker/my.cnf:/etc/mysql/my.cnf
        networks:
            - martin-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: martin.phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_USER: "martin"
            MYSQL_PASSWORD: "123123"
        ports:
            - "8482:80"

    redis:
        image: redis:latest
        container_name: martin.redis
        volumes:
            - redisdata:/data
        ports:
            - "6377:6379"

volumes:
    mysqldata:
        driver: "local"
    redisdata:
        driver: "local"
    phpmyadmindata:
        driver: "local"

networks:
    martin-network:
        driver: bridge
