version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: martin/php
        container_name: martin.app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        networks:
            - martin-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: martin.webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8087:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - martin-network

    #MySQL Service
    db:
        image: mysql:8.0.33
        container_name: martin.db
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: your_root_password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - martin-network

    redis:
        image: redis:latest
        container_name: martin.redis
        volumes:
            - redisdata:/data
        ports:
            - "6377:6379"

#Docker Networks
networks:
    martin-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
    redisdata:
        driver: local
